In [1]:
#Loaded Nedded Libraries
import numpy as np 
from scipy.io import loadmat
#Read The Data 
data = loadmat('D:\\Programming\\Machine Learning Projects\\My Projects\\Data\\5- Classifiication With Multivariables.mat')
print(data)
print('***'*40)
print('The Shape Of Matrix X Is ==> ',data['X'].shape)#The Shape Of Matrix X Is ==>  (5000, 400)
print('\t\t The Matrix Of X Is \n',data['X'])
print('***'*40)
print('The Shape Of Matrix Y Is ==> ',data['y'].shape)#The Shape Of Matrix Y Is ==>  (5000, 1)
print('\t\t The Matrix Of Y Is \n',data['y'])
print('***'*40)
print('\t\t The Row One In Matrix X Is \n',data['X'][0])
print('***'*40)
print('The Information Number 156 In Row 0 In Matrix X Is ==> ',data['X'][0][155]) #The Information Number 156 In Row 0 In Matrix X Is ==>  0.9017626506597092

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011', '__version__': '1.0', '__globals__': [], 'X': array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 'y': array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)}
************************************************************************************************************************
The Shape Of Matrix X Is ==>  (5000, 400)
		 The Matrix Of X Is 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
************************************************************************************************************************
The Shape Of Matrix Y Is ==>  (5000, 1)
		

In [2]:
#Make Sigmoid Function 
def sigmoid_func(num) : return 1 / (1 + np.exp(-num))
#==============================================================
#Make Cost Function 
def cost_function (theta , x , y , alpha):
    theta_values =np.matrix(theta)
    x_values = np.matrix(x)
    y_values = np.matrix(y)
    first_eq = np.multiply(- y_values , np.log(sigmoid_func(x_values * theta_values.T)))
    second_eq = np.multiply((1 - y) ,np.log((1- sigmoid_func(x_values * theta_values.T))))
    reg_eq = (alpha / 2 * len(x_values)) * np.sum(np.power(theta_values[:,1:theta_values.shape[1]] , 2))
    return np.sum (first_eq - second_eq) / len (x_values) +reg_eq

In [5]:
def gradient_descent_with_loop(theta , x , y , alpha):
    theta_value=np.matrix(theta)
    x_value = np.matrix(x)
    y_value = np.matrix(y)
    parameters = int(theta_value.ravel().shape[1])
    grad=np.zeros(parameters)
    error =sigmoid_func(x_value * theta_value.T) - y_value
    for i in range (parameters):
        term=np.multiply(error ,x_value[: , i])
        if (i == 0): grad[i] = np.sum(term) / len (x_value)
        else : grad[i] = (np.sum(term) / len(x_value)) + (( alpha / len(x_value)) * theta_value[:,i] )
    return grad

In [7]:
def GD(theta , x, y , lr):
    theta_values = np.matrix(theta)
    x_values = np.matrix(x)
    y_values = np.matrix(y)
    paramters = int (theta_values.ravel().shape[1])
    error = sigmoid_func(x_values * theta_values.T) -y_values
    grad = ((x_values.T * error) / len(x_values)).T + (( lr / len(x_values)) * theta_values)
    #Intercept gradient is not reguarlized
    grad [0,0] = np.sum(np.multiply(error , x_values[:,0])) / len(x_values)
    return np.array(grad).ravel()

In [12]:
from scipy.optimize import minimize
def one_vs_all (x , y , num_labels , learning_rate):
    rows =x.shape[0]#5000
    params =x.shape[1]#400
    #K X (N +1) array for paramters of each of the k classifiers
    all_theta =np.zeros((num_labels,params+1))
    print('All Theta Shape ==> ',all_theta.shape)#
    #Insert a column of ones at the beginning for the intercept term 
    x = np.insert(x,0,values=np.ones(rows),axis =1)
    print('The Shape Of Matrix X Is ==> ',x.shape)#
    #Labels Are 1 -Indeeded Instead of 0-Indeeded
    for i in range( 1 , num_labels + 1):
        theta =np.zeros(params + 1)
        y_i = np.array( [ 1 if label == i else  0 for label in y])
        y_i = np.reshape(y_i , (rows ,1))
        #Minimize the objective function 
        fmin = minimize(fun=cost_function , x0 =theta ,args=(x ,y_i , learning_rate),method='TNC',jac =GD)
        all_theta[i-1:] =fmin.x
    return all_theta

In [3]:
#Treatment With Data X 
rows = data['X'].shape[0]
params =data['X'].shape[1]
print('The Rows Is = ',rows)#The Rows Is =  5000
print('The Parameters is = ',params)#The Parameters is =  400
print('==='*60)
all_theta=np.zeros((10,params+1))
print('The Shape Of Matrix All Theta Is ==> ',all_theta.shape)#The Shape Of Matrix All Theta Is ==>  (10, 401)
print('\t\t The Matrix Of All Theta Is \n',all_theta)
print('***'*60)
#Make Insert Value Of X0 In Matrix X 
x_data = np.insert(data['X'],0,values=np.ones(rows),axis=1)
print('The Shape Of Matrix X After Add The Value Of X0 Is ==> ',x_data.shape)#The Shape Of Matrix X After Add The Value Of X0 Is ==>  (5000, 401)
print('\t\t The Matrix Of X After Add The Value Of X0 Is \n',x_data)
print('***'*60)
#Make Matrix Of Theta Is Dimensional Is Equal No Of Paramters +1 , in the End Is = 401
theta =np.zeros(params+1)
print('The Shape Of Matrix Theta Is ==> ',theta.shape)
print('\t\t The Matrix Of Theta Is \n',theta)
print('***'*60)

The Rows Is =  5000
The Parameters is =  400
The Shape Of Matrix All Theta Is ==>  (10, 401)
		 The Matrix Of All Theta Is 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
************************************************************************************************************************************************************************************
The Shape Of Matrix X After Add The Value Of X0 Is ==>  (5000, 401)
		 The Matrix Of X After Add The Value Of X0 Is 
 [[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
************************************************************************************************************************************************************************************
The Shape Of Matrix Theta Is ==>  (401,)
		 The Matrix Of Theta Is 
 [0. 0. 0. 0. 0

In [14]:
#Treatment The Matrix Of Y 
y_0 =np.array( [1 if label == 0 else 0 for label in data ['y']] )
print('The Shape Of Matrix y_0 Is ==> ',y_0.shape)#The Shape Of Matrix y_0 Is ==>  (5000,)
print('\t\t The Matrix Of Y0 Is \n',y_0)
print('***'*60)
#Make Reshape The Matrix Of Y0 
y0_reshape =np.reshape(y_0,(rows,1))
print('The Shape Matrix Y0 After Make Reshape Is ==>  ',y0_reshape.shape)#The Shape Matrix Y0 After Make Reshape Is ==>   (5000, 1)
print('\t\t The Matrix Y0_reshape Is \n',y0_reshape)
print('***'*60)
print('\t\t\t The Shape Of All Matrix ')
print('The Matrix Of X_data Shape Is ==> ',x_data.shape)#The Matrix Of X_data Shape Is ==>  (5000, 401)
print('The Shape Of Matrix y0_reshape Is ==> ',y0_reshape.shape)#The Shape Of Matrix y0_reshape Is ==>  (5000, 1)
print('The Shape Of Matrix Theta Is ==> ',theta.shape)#The Shape Of Matrix Theta Is ==>  (401,)
print('The Shape Of Matrix All Theta Is ==> ',all_theta.shape)#The Shape Of Matrix All Theta Is ==>  (10, 401)
print('The Data Array Of Y But Unique Is ==> ',np.unique(data['y']))#The Data Array Of Y But Unique Is ==>  [ 1  2  3  4  5  6  7  8  9 10]
print('***'*60)


The Shape Of Matrix y_0 Is ==>  (5000,)
		 The Matrix Of Y0 Is 
 [0 0 0 ... 0 0 0]
************************************************************************************************************************************************************************************
The Shape Matrix Y0 After Make Reshape Is ==>   (5000, 1)
		 The Matrix Y0_reshape Is 
 [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
************************************************************************************************************************************************************************************
			 The Shape Of All Matrix 
The Matrix Of X_data Shape Is ==>  (5000, 401)
The Shape Of Matrix y0_reshape Is ==>  (5000, 1)
The Shape Of Matrix Theta Is ==>  (401,)
The Shape Of Matrix All Theta Is ==>  (10, 401)
The Data Array Of Y But Unique Is ==>  [ 1  2  3  4  5  6  7  8  9 10]
**************************************************************************************************************************************************

In [13]:
all_theta = one_vs_all(data['X'],data['y'] , 10 , 1)
print('The All Theta Shape Is ==> ',all_theta.shape)#
print('\t\t The All Theta Is \n',all_theta)
def prdict_all (x, all_theta):
    rows = x.shape[0]
    params =x.shape[1]
    num_labels = all_theta.shape[0]
    #Same as before , insert ones to match the shape 
    x = np.insert(x , 0 , values= np.ones(rows),axis =1)
    #Convert To Matrix Because To Easily Treatment
    x_new = np.matrix(x)
    all_theta_new = np.matrix(all_theta)
    #Compute The Class Probability For Each Class on Each Training Instance 
    h =sigmoid_func(x_new * all_theta_new.T)
    #Create Array of the index with the maximum probability 
    h_argmax = np.argmax(h , axis = 1)
    #Because Our Array was zero-indexed we need to add one for the true label prediction 
    h_argmax =h_argmax + 1
    return h_argmax


All Theta Shape ==>  (10, 401)
The Shape Of Matrix X Is ==>  (5000, 401)
The All Theta Shape Is ==>  (10, 401)
		 The All Theta Is 
 [[-3.70247929e-05  0.00000000e+00  0.00000000e+00 ... -2.24803602e-10
   2.31962906e-11  0.00000000e+00]
 [-8.96250717e-05  0.00000000e+00  0.00000000e+00 ...  7.26120807e-09
  -6.19965281e-10  0.00000000e+00]
 [-8.39553414e-05  0.00000000e+00  0.00000000e+00 ... -7.61695666e-10
   4.64917672e-11  0.00000000e+00]
 ...
 [-7.00832425e-05  0.00000000e+00  0.00000000e+00 ... -6.92009010e-10
   4.29241485e-11  0.00000000e+00]
 [-7.65187961e-05  0.00000000e+00  0.00000000e+00 ... -8.09503302e-10
   5.31058737e-11  0.00000000e+00]
 [-6.63412819e-05  0.00000000e+00  0.00000000e+00 ... -3.49766235e-09
   1.13668661e-10  0.00000000e+00]]


In [14]:
y_pred = prdict_all(data['X'],all_theta)
correct = [ 1 if a == b else 0 for (a , b ) in zip (y_pred , data ['y'])]
accuracy = (sum (map ( float ,correct)) / float (len (correct)))
print('The Accuracy Is = {0} % '.format(accuracy * 100))

The Accuracy Is = 74.6 % 
